# Generated by Django 3.1.6 on 2021-02-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210210_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='authorized_keys',
            field=models.TextField(),
        ),
    ]
