apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      run: frontend
  replicas: 1
  template:
    metadata:
      labels:
        run: frontend
    spec:
      containers:
      - name: frontend
        image: frontend
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: PGPASSWORD
          value: 41e8b73cbfc568deb1aa01592c600c66
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    run: frontend
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    run: frontend

