apiVersion: apps/v1
kind: Deployment
metadata:
  name: sshd-deployment
spec:
  selector:
    matchLabels:
      run: sshd
  replicas: 1
  template:
    metadata:
      labels:
        run: sshd
    spec:
      containers:
      - name: sshd
        image: sshd
        imagePullPolicy: Never
        ports:
        - containerPort: 2222
---
apiVersion: v1
kind: Service
metadata:
  name: sshd-service
  labels:
    run: sshd
spec:
  ports:
  - port: 2222
  selector:
    run: sshd

